feat: 게시글 목록 조회 기능 구현
project-study-ssafy/backend pull request #44
Opened 2024-11-15 01:14 UTC by UnrequiredOne

resolved : #43

## 개요 :mag:
- 게시글의 목록 조회 기능을 구현했습니다.
## 작업사항 :memo:
- 게시판 ID에 따른 게시글의 목록 조회 기능 구현
- 게시글 목록 조회 API 구현

2024-11-15 01:30 UTC, jongchan0109 requested changes

2024-11-15 01:30 UTC, jongchan0109 commented on src/main/java/com/ssafeople/backend/domain/post/domain/Post.java
>          user.getPosts().add(this);
board에도 post와 연관관계를 맺는 것은 어떨까요?

2024-11-15 01:30 UTC, jongchan0109 commented on src/main/java/com/ssafeople/backend/domain/post/presentation/PostController.java
> +    public ResponseEntity<List<Post>> getPostsByBoard(@RequestParam(required = true) Short boardId) {
@RequestParam(required = true) 로 boardId 를 받는 것도 좋지만, REST API에서는 주로 PathVariable 방식을 더 많이 사용하는 것 같아요

2024-11-15 01:30 UTC, jongchan0109 commented on src/main/java/com/ssafeople/backend/domain/post/service/PostServiceImpl.java
> +    @Override
@Transactional(readOnly = true) 를 작성하는 것이 좋을 것 같아요!

2024-11-15 01:30 UTC, jongchan0109 commented on src/main/java/com/ssafeople/backend/global/exception/post/PostListEmptyException.java
> +    public PostListEmptyException() {
싱글톤 패턴을 사용하시려는 것 같은데, private 접근자가 좋을 것 같아요!

2024-11-15 01:30 UTC, jongchan0109 commented on src/test/java/com/ssafeople/backend/domain/post/service/PostServiceImplTest.java
> +    @DisplayName("게시글 목록 반환 실패")
으흠...

2024-11-15 01:31 UTC, UnrequiredOne commented on src/test/java/com/ssafeople/backend/domain/post/service/PostServiceImplTest.java
> +    @DisplayName("게시글 목록 반환 실패")
어음

2024-11-16 07:20 UTC, jongchan0109 reviewed
승인합니다.

2024-11-16 07:20 UTC, jongchan0109 approved these changes

2024-11-16 08:25 UTC, merged